framework:
    workflows:
        demande_publishing:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments:
                    - 'status'
            supports:
                - App\Entity\Demande
                - App\Demande\DemandeRequest
            initial_place: draft
            places:
                - draft
                - review
                - editor
                - editor_ok
                - refused
                - published
            transitions:
                to_review:
                    from: draft
                    to:   review
                to_approval:
                    from: review
                    to:   editor
                editor_approuved:
                    from: editor
                    to:   editor_ok
                editor_fail:
                    from: editor
                    to:   review
                editor_refused:
                    from: editor
                    to:   refused
                to_be_published:
                    from: editor_ok
                    to:   published

